import requests

headers = {
    'authority': 'www.cogornogolf.com',
    'pragma': 'no-cache',
    'cache-control': 'no-cache',
    'sec-ch-ua': '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"',
    'x-thinkific-client-app-version': '3e9547b40243ba6df4212abda625af4c559f966c',
    'x-thinkific-client-date': '2021-10-22T16:10:55.208Z',
    'dnt': '1',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
    'accept': 'application/json',
    'x-client-id': 'KOBAYASHI',
    'x-requested-with': 'XMLHttpRequest',
    'sec-ch-ua-platform': '"Linux"',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.cogornogolf.com/courses/take/Diagnose-Your-Flaw-Downswing/lessons/5555678-arms-not-in-the-slot',
    'accept-language': 'ru,en-US;q=0.9,en;q=0.8,uk;q=0.7,no;q=0.6,nb;q=0.5,nn;q=0.4,bg;q=0.3,af;q=0.2',
    'cookie': 'visitor_id=1072270699; remember_user_token=BAhbCFsGaQTBDGMDSSIiJDJhJDEwJGNPOU1mTlBzVWEvT3JFeVRoODlXeXUGOgZFVEkiFzE2MzQ4MjAxNzguNTQwNTM4NQY7AEY%3D--cbec7ab240382078939eda9b25426ca03421180b; _thinkific_session=akROVU9yLzc2VEhKSUxiejBtNVBXN0E0cUFtc0MwRXlFSVFLS0pqbVliV1Arb3E4NzBqZFA4WmcreFd4RE52VU1PbndYeXpsdWt1MWpSS2NpNjlkVDRsRTExTzFTK2tua1lQY0hBQm5lY2VtdjBvZWc4YmVZUGZTblRNTkxOR25Qek1hNUxZYk5mR0NHYURhT2txY1c4Q2R2ZGlqMlF4V1ZUamUzeUNDb2RiT1RReWd4Q0dGL05oVWpLYmg2SHlHbkk4WEx5M01pTWdvaStlVGZ3STVKalhoaE5IdW51MUhQUis0bnl3T1NxUU56OGtjMi9RUjBrdC9Ca3MvZ1JTb3JWN0k4TEFxeXEyek1hT3VYcHQ5TGFEcEFRM1AxQXhueTJjSUxzbWo5WUM5b2t2amhFbWpGNzEvR2ZTRE9OUW5BWndPaGt0Mm5peitkekdwaXlMZUExYmFJYVBzL0pQb0J6ZFkrRlkrV01nNXkremRDbnRMc0ErK1lQWm9JVU1ITGo3aUtTb3A3SzIyUG40K3BpMXY1QT09LS10SHNEV3JuMW9WS2JxbG4wY3dyUTdBPT0%3D--afa4d8f961f84df7286b8eaa826ccd42645441b6',
}

list_topics = [
'quick-fix-chunked-chips',
'wedge-short-iron-master-class',
'golf-swing-for-seniors-master-class',
'fairway-woods-hybrids-master-class',
'laser-like-irons-fix-your-push',
'Diagnose-Your-Flaw-Downswing',
'draw-every-ball-master-class',
'live-golf-lessons',
'quick-fix-slice',
'Shallowing-Downswing',
'Compression',
'Incorporating-The-Body',
'Short-Game-Genius-Guide',
'Shot-Making',
'quick-fix-shallowing',
'drills-feels-flip',
'Grip',
'Practice-Fundamentals',
'Perfecting-A-Repeatable-Stroke',
'Generating-Speed-Distance',
'quick-fix-eliminating-early-extension',
'core-practice-putting',
'core-practice-speed-power',
'core-practice-accuracy-consistency',
'core-practice-short-game',
'quick-fix-accuracy-consistency',
'quick-fix-course-mgmt',
'quick-fix-breaking-80',
'quick-fix-wedges',
'quick-fix-bounce',
'quick-fix-bunker',
'quick-fix-speed-control',
'quick-fix-putting-stroke',
'quick-fix-shank',
'quick-fix-topped-thin',
'quick-fix-push',
'quick-fix-pull',
'quick-fix-hook',
'quick-fix-fat-heavy',
'quick-fix-swing-model',
'quick-fix-speed',
'quick-fix-sway',
'quick-fix-flip',
'core-practice-ball-striking',
'quick-fix-steep-over-top',
'early-extension-quick-fix',
'drills-feels-sway',
'drills-feels-rotation',
'drills-feels-over-the-top',
'drills-feels-early-extension',
'drills-feels-shallowing',
'drills-feels-takeaway',
'drills-feels-fat-heavy',
'drills-feels-shank',
'drills-feels-tops',
'drills-feels-push',
'drills-feels-pull',
'drills-feels-slice',
'drills-feels-hook',
'drills-feels-compression',
'slide-quick-fix',
'Green-Reading',
'Diagnose-Your-Flaw-Backswing',
'Staying-Centered',
'Backswing-Mechanics',
'Mastering-Putting-Practice',
'Increasing-Make-Percentage',
'Speed-Control',
'Bunker-Play',
'Short-Game-Practice',
'Practicing-Wedges',
'Rotation',
'Distance-Control',
'Drivers-Woods',
'Wrist-Conditions',
'Hand-Depth',
'Diagnose-Your-Flaw-Setup',
'Scoring-Opportunities',
'Practice-Like-A-Pro',
'Path-and-Start-Line',
'Trajectory-Control-Chipping',
'Wedge-System',
'Direction-Trajectory-Control',
'Downswing-Mechanics',
'ball-position',
'Body-Positioning',
'Pre-Shot-Musts',
'Diagnose-Your-Flaw-Chipping',
'Putting-Set-Up',
'Wedge-Basics',
'Diagnose-Your-Flaw-Ball-Pattern',
'Starting-The-Downswing',
'The-One-Piece-Takeaway',
'Stock-Chipping',
'shallowing-your-downswing-master-class',
'rotation-master-class',
'early-extension-master-class',
'slice-fix-master-class',
'distance-master-class',
'speed-master-class',
'putting-master-class-level-1-speed-management',
'compression-master-class',
'eric-s-ultimate-full-swing-blueprint',
'eric-cogorno-s-ultimate-putting-practice-plan',
'eric-cogorno-s-ultimate-chipping-practice-plan',
'eric-cogorno-s-ultimate-full-swing-range-practice-plan',
'driver-club-fitting-master-class',
]
for topic in list_topics:
    response = requests.get('https://www.cogornogolf.com/api/course_player/v2/courses/' + topic, headers=headers)
    with open (topic + '.json', 'w') as f:
        f.write(response.text)